import "server-only";import { canonicalSneakerKey,type CanonicalSneakerKey } from "../../domain/identity/canonicalSneaker";import { DAILY_PICK_ALGORITHM_VERSION,scoreDailyPick,selectDiverseDailyPicks,type DailyPickContext } from "../../domain/daily-picks/dailyPicks";import type { ReleaseCandidate,ReleaseInformationState } from "../../domain/release/release";import { internalAdmin } from "../../infrastructure/repositories/dailyPickRepository";
export async function buildDailyBatch(userId:string,targetDate:string){if(!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(targetDate))throw new Error("INVALID_DATE");const db=await internalAdmin();const existing=await db.from("daily_pick_batches").select("id").eq("user_id",userId).eq("target_date",targetDate).eq("algorithm_version",DAILY_PICK_ALGORITHM_VERSION).maybeSingle();if(existing.data)return{batchId:existing.data.id,created:false,count:0};
 const [releaseResult,prefResult,ownedResult,wishResult,feedbackResult]=await Promise.all([db.from("release_items").select("*,release_variants(*),release_evidence(*)").neq("information_state","cancelled"),db.from("user_preferences").select("*").eq("user_id",userId).maybeSingle(),db.from("owned_sneakers").select("brand,model_name,model_family,generation,style_code,audience").eq("user_id",userId),db.from("wishlist_items").select("brand,model_name,model_family,generation,style_code,audience").eq("user_id",userId),db.from("recommendation_feedback").select("canonical_key").eq("user_id",userId).in("sentiment",["disliked","hidden"])]);
 const pref=prefResult.data??{};const key=(r:Record<string,unknown>)=>canonicalSneakerKey({brand:String(r.brand??""),modelName:String(r.model_name??""),modelFamily:String(r.model_family??""),generation:typeof r.generation==="string"?r.generation:null,styleCode:typeof r.style_code==="string"?r.style_code:null,audience:(r.audience??"unknown") as never});
 const context:DailyPickContext={favoriteBrands:strings(pref.favorite_brands),avoidedBrands:strings(pref.avoided_brands),favoriteColors:strings(pref.favorite_colors),avoidedColors:strings(pref.avoided_colors),favoriteMaterials:strings(pref.favorite_materials),avoidedMaterials:strings(pref.avoided_materials),budgetMaxJpy:typeof pref.budget_max_jpy==="number"?pref.budget_max_jpy:null,budgetIsHardLimit:Boolean(pref.budget_is_hard_limit),owned:(ownedResult.data??[]).map((r)=>key(r as Record<string,unknown>)),wishlist:(wishResult.data??[]).map((r)=>key(r as Record<string,unknown>)),disliked:(feedbackResult.data??[]).map((r)=>r.canonical_key as CanonicalSneakerKey)};
 const candidates=(releaseResult.data??[]).map(mapRelease);const scored=candidates.map((c)=>scoreDailyPick(c,context)).filter((v)=>v!==null);const picks=selectDiverseDailyPicks(scored);const {data:batch,error}=await db.from("daily_pick_batches").insert({user_id:userId,target_date:targetDate,preference_version:String(pref.updated_at??"none"),algorithm_version:DAILY_PICK_ALGORITHM_VERSION}).select("id").single();if(error){if(error.code==="23505"){const retry=await db.from("daily_pick_batches").select("id").eq("user_id",userId).eq("target_date",targetDate).eq("algorithm_version",DAILY_PICK_ALGORITHM_VERSION).single();return{batchId:retry.data?.id,created:false,count:0}}throw new Error("BATCH_WRITE_FAILED")}
 if(picks.length){const {error:pickError}=await db.from("daily_picks").insert(picks.map((p,index)=>({batch_id:batch.id,release_item_id:p.candidate.id,rank:index+1,total_score:p.score.total,score_breakdown:p.score,explanation:p.explanation,verification_state:p.candidate.verificationState})));if(pickError)throw new Error("PICKS_WRITE_FAILED")}
 return{batchId:batch.id,created:true,count:picks.length};}
function mapRelease(row:Record<string,unknown>):ReleaseCandidate{const variants=Array.isArray(row.release_variants)?row.release_variants as Record<string,unknown>[]:[];const variant=variants[0]??{};const evidence=Array.isArray(row.release_evidence)?row.release_evidence as Record<string,unknown>[]:[];const brand=String(row.canonical_brand),modelName=String(row.canonical_model_name);return{id:String(row.id),key:canonicalSneakerKey({brand,modelName,modelFamily:String(row.model_family),generation:typeof row.generation==="string"?row.generation:null,styleCode:typeof variant.style_code==="string"?variant.style_code:null,audience:(variant.audience??"unknown") as never}),brand,modelName,colorwayName:typeof variant.colorway_name==="string"?variant.colorway_name:null,informationState:row.information_state as ReleaseInformationState,releaseDate:typeof row.release_date==="string"?row.release_date:null,verificationState:(variant.verification_state??"model_only") as ReleaseCandidate["verificationState"],sourceConfidence:Number(row.source_confidence??0),evidenceCount:evidence.length,priceJpy:null,tags:[],colors:[],materials:[]}}
function strings(v:unknown){return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[]}
