"use client";
import { useEffect, useState, type FormEvent } from "react";

function split(value: FormDataEntryValue | null) { return String(value ?? "").split(",").map((item)=>item.trim()).filter(Boolean); }
export function PreferencesForm(){const [message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={favoriteBrands:split(f.get("favoriteBrands")),avoidedBrands:split(f.get("avoidedBrands")),favoriteColors:split(f.get("favoriteColors")),avoidedColors:split(f.get("avoidedColors")),favoriteMaterials:split(f.get("favoriteMaterials")),avoidedMaterials:split(f.get("avoidedMaterials")),silhouettes:split(f.get("silhouettes")),useCases:split(f.get("useCases")),styleTags:split(f.get("styleTags")),budgetMinJpy:f.get("budgetMinJpy")?Number(f.get("budgetMinJpy")):null,budgetMaxJpy:f.get("budgetMaxJpy")?Number(f.get("budgetMaxJpy")):null,budgetIsHardLimit:f.get("budgetIsHardLimit")==="on",conditionPreference:f.get("conditionPreference")};const r=await fetch("/api/me/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?"好みを保存しました。":"保存できませんでした。")}return <form className="settings-panel" onSubmit={submit}><p>項目はカンマ区切りで入力できます。推定した好みは明示した好みを上書きしません。</p>{[["favoriteBrands","好きなブランド"],["avoidedBrands","避けたいブランド"],["favoriteColors","好きな色"],["avoidedColors","避けたい色"],["favoriteMaterials","好きな素材"],["avoidedMaterials","避けたい素材"],["silhouettes","シルエット"],["useCases","用途"],["styleTags","スタイル"]].map(([name,label])=><label key={name}>{label}<input name={name}/></label>)}<label>予算の下限<input name="budgetMinJpy" type="number" min="0"/></label><label>予算の上限<input name="budgetMaxJpy" type="number" min="0"/></label><label><input name="budgetIsHardLimit" type="checkbox"/> 上限を必須条件にする</label><label>状態<select name="conditionPreference"><option value="either">どちらでも</option><option value="new">新品</option><option value="used">中古</option></select></label><button>保存する</button><p aria-live="polite">{message}</p></form>}

type CollectionKind="owned"|"wishlist";
export function SneakerCollection({kind}:{kind:CollectionKind}){const endpoint=kind==="owned"?"/api/me/owned-sneakers":"/api/me/wishlist";const [items,setItems]=useState<Record<string,unknown>[]>([]);const [message,setMessage]=useState("");async function load(){const r=await fetch(endpoint,{cache:"no-store"});if(r.ok){const j=await r.json();setItems(j.data.items)}}useEffect(()=>{void load()},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const common={brand:f.get("brand"),modelName:f.get("modelName"),modelFamily:f.get("modelFamily"),generation:null,colorwayName:f.get("colorwayName")||null,styleCode:f.get("styleCode")||null,audience:f.get("audience")||"unknown",notes:f.get("notes")||null};const body=kind==="owned"?{...common,sizeSystem:null,sizeValue:null,userRating:null,wearFrequency:null}:{...common,desiredSizeSystem:null,desiredSizeValue:null,budgetMaxJpy:null,priority:3,verificationState:"unverified"};const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?"追加しました。":"追加できませんでした。");if(r.ok){e.currentTarget.reset();await load()}}return <><form className="settings-panel" onSubmit={submit}><label>ブランド<input name="brand" required maxLength={80}/></label><label>モデル<input name="modelName" required maxLength={160}/></label><label>モデルファミリー<input name="modelFamily" required maxLength={120}/></label><label>カラー<input name="colorwayName" maxLength={160}/></label><label>Style Code<input name="styleCode" maxLength={40}/></label><label>対象<select name="audience"><option value="unknown">未確認</option><option value="men">メンズ</option><option value="women">ウィメンズ</option><option value="unisex">ユニセックス</option><option value="kids">キッズ</option></select></label><label>メモ<textarea name="notes" maxLength={1000}/></label><button>追加する</button><p aria-live="polite">{message}</p></form><section aria-label="登録済み"><h2>登録済み</h2>{items.length===0?<p>まだ登録がありません。</p>:<ul>{items.map((item)=><li key={String(item.id)}>{String(item.brand)} {String(item.model_name)}</li>)}</ul>}</section></>}

export function NotificationForm(){const [m,setM]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/me/notification-settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({frequency:f.get("frequency"),timezone:f.get("timezone"),quietHoursStart:null,quietHoursEnd:null,rumorAllowed:f.get("rumorAllowed")==="on"})});setM(r.ok?"設定を保存しました。配送はまだ無効です。":"保存できませんでした。")}return <form className="settings-panel" onSubmit={submit}><p>通知の配送はこのバージョンでは無効です。将来利用する設定だけを保存します。</p><label>頻度<select name="frequency"><option value="off">オフ</option><option value="daily">毎日</option><option value="weekly">毎週</option></select></label><label>タイムゾーン<input name="timezone" defaultValue="Asia/Tokyo"/></label><label><input type="checkbox" name="rumorAllowed"/> 未確定情報を含める</label><button>設定を保存</button><p aria-live="polite">{m}</p></form>}
