import type { GeminiExplanationInput } from "./types";

export function createGeminiExplanationPrompt(
  input: GeminiExplanationInput
): string {
  const { result, fallback } = input;

  const facts = {
    sneakerId: result.sneakerId,
    name: result.name,
    finalDecision: result.finalDecision,
    rawDecision: result.rawDecision,
    demotions: result.demotions,
    finalScore: result.scoreBreakdown.finalScore,
    scoreBreakdown: result.scoreBreakdown,
    fallbackExplanation: {
      summary: fallback.summary,
      reasons: fallback.reasons,
      cautions: fallback.cautions,
    },
  };

  return [
    "You are an explanation-polishing adapter for SOLE//MATRIX Core v0.2.",
    "Your only job is to rewrite the existing rule-based explanation into natural Japanese.",
    "",
    "Use only the facts generated by the Core recommendation engine below.",
    "Do not add new facts, external market knowledge, or assumptions.",
    "",
    "Strict prohibitions:",
    "- Do not change, reinterpret, recalculate, or override any score.",
    "- Do not change finalDecision.",
    "- Do not change rawDecision.",
    "- Do not change demotions.",
    "- Do not state or imply real-world prices.",
    "- Do not state or imply stock availability.",
    "- Do not state or imply resale premiums or resale value.",
    "- Do not judge authenticity, legit checks, real/fake status, or official provenance.",
    "- Do not say the user should absolutely buy it.",
    "",
    "Return JSON only. Do not include markdown, comments, score fields, decision fields, sneakerId, or name.",
    "The JSON schema is:",
    '{ "summary": string, "reasons": string[], "cautions": string[] }',
    "",
    "Core facts and fallback explanation:",
    JSON.stringify(facts, null, 2),
  ].join("\n");
}

