export const samplePreferenceProfiles = {
  caseA: {
    userId: "sample_user_a",
    vector: {
      culture: 60,
      styleFit: 80,
      simplicity: 85,
      street: 30,
      volume: 20,
      comfort: 65,
      durability: 70,
    },
    policy: {
      priceSensitivity: 85,
      overlapSensitivity: 80,
      explorationTolerance: 30,
    },
    axisImportance: {
      culture: 60,
      styleFit: 80,
      simplicity: 85,
      street: 40,
      volume: 40,
      comfort: 70,
      durability: 65,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
  caseB: {
    userId: "sample_user_b",
    vector: {
      culture: 55,
      styleFit: 60,
      simplicity: 35,
      street: 90,
      volume: 85,
      comfort: 55,
      durability: 50,
    },
    policy: {
      priceSensitivity: 45,
      overlapSensitivity: 50,
      explorationTolerance: 80,
    },
    axisImportance: {
      culture: 45,
      styleFit: 60,
      simplicity: 35,
      street: 95,
      volume: 95,
      comfort: 45,
      durability: 40,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
  caseC: {
    userId: "sample_user_c",
    vector: {
      culture: 40,
      styleFit: 60,
      simplicity: 55,
      street: 30,
      volume: 40,
      comfort: 90,
      durability: 90,
    },
    policy: {
      priceSensitivity: 80,
      overlapSensitivity: 60,
      explorationTolerance: 35,
    },
    axisImportance: {
      culture: 30,
      styleFit: 60,
      simplicity: 50,
      street: 30,
      volume: 40,
      comfort: 100,
      durability: 95,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
  caseD: {
    userId: "sample_user_d",
    vector: {
      culture: 70,
      styleFit: 80,
      simplicity: 80,
      street: 40,
      volume: 25,
      comfort: 75,
      durability: 75,
    },
    policy: {
      priceSensitivity: 25,
      overlapSensitivity: 100,
      explorationTolerance: 30,
    },
    axisImportance: {
      culture: 60,
      styleFit: 85,
      simplicity: 80,
      street: 40,
      volume: 35,
      comfort: 70,
      durability: 70,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
  caseE: {
    userId: "sample_user_e",
    vector: {
      culture: 70,
      styleFit: 80,
      simplicity: 75,
      street: 50,
      volume: 40,
      comfort: 80,
      durability: 80,
    },
    policy: {
      priceSensitivity: 100,
      overlapSensitivity: 20,
      explorationTolerance: 40,
    },
    axisImportance: {
      culture: 60,
      styleFit: 80,
      simplicity: 70,
      street: 50,
      volume: 40,
      comfort: 70,
      durability: 70,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
  caseF: {
    userId: "sample_user_f",
    vector: {
      culture: 80,
      styleFit: 85,
      simplicity: 70,
      street: 60,
      volume: 50,
      comfort: 40,
      durability: 80,
    },
    policy: {
      priceSensitivity: 15,
      overlapSensitivity: 20,
      explorationTolerance: 30,
    },
    axisImportance: {
      culture: 80,
      styleFit: 85,
      simplicity: 65,
      street: 60,
      volume: 50,
      comfort: 25,
      durability: 75,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
  caseG: {
    userId: "sample_user_g",
    vector: {
      culture: 80,
      styleFit: 85,
      simplicity: 70,
      street: 60,
      volume: 50,
      comfort: 80,
      durability: 40,
    },
    policy: {
      priceSensitivity: 15,
      overlapSensitivity: 20,
      explorationTolerance: 30,
    },
    axisImportance: {
      culture: 80,
      styleFit: 85,
      simplicity: 65,
      street: 60,
      volume: 50,
      comfort: 75,
      durability: 25,
    },
    sourceConfidence: {
      diagnosis: 60,
      ownedSneakers: 75,
      wantedSneakers: 45,
      feedback: 70,
    },
    profileVersion: 1,
    updatedAt: "2026-06-09T00:00:00Z",
  },
} as const;
