export const sampleSneakerVectors = {
  caseA: {
    A1_canvas_high_overlap: {
      sneakerId: "A1_canvas_high_overlap",
      name: "Canvas Low-Tech High Overlap",
      vector: {
        culture: 65,
        styleFit: 85,
        simplicity: 90,
        street: 25,
        volume: 20,
        comfort: 55,
        durability: 65,
        priceLevel: 35,
      },
      tags: ["low_tech", "canvas", "classic", "minimal"],
      budgetFit: 80,
    },
    A2_expensive_collab: {
      sneakerId: "A2_expensive_collab",
      name: "Expensive Retro Collab",
      vector: {
        culture: 85,
        styleFit: 75,
        simplicity: 50,
        street: 75,
        volume: 60,
        comfort: 45,
        durability: 50,
        priceLevel: 90,
      },
      tags: ["collab", "retro", "street"],
      budgetFit: 80,
    },
    A3_comfortable_simple_runner: {
      sneakerId: "A3_comfortable_simple_runner",
      name: "Comfortable Simple Runner",
      vector: {
        culture: 45,
        styleFit: 75,
        simplicity: 80,
        street: 35,
        volume: 35,
        comfort: 85,
        durability: 80,
        priceLevel: 55,
      },
      tags: ["running", "minimal", "comfortable"],
      budgetFit: 80,
    },
  },
  caseB: {
    B1_chunky_street: {
      sneakerId: "B1_chunky_street",
      name: "Chunky Street Basketball",
      vector: {
        culture: 60,
        styleFit: 65,
        simplicity: 25,
        street: 95,
        volume: 90,
        comfort: 65,
        durability: 60,
        priceLevel: 65,
      },
      tags: ["street", "chunky", "basketball"],
      budgetFit: 80,
    },
    B2_clean_lowtech_safe: {
      sneakerId: "B2_clean_lowtech_safe",
      name: "Clean Low-Tech Safe Choice",
      vector: {
        culture: 50,
        styleFit: 80,
        simplicity: 90,
        street: 25,
        volume: 20,
        comfort: 70,
        durability: 65,
        priceLevel: 40,
      },
      tags: ["minimal", "classic", "low_tech"],
      budgetFit: 80,
    },
    B3_trail_discovery: {
      sneakerId: "B3_trail_discovery",
      name: "Trail Outdoor Discovery",
      vector: {
        culture: 55,
        styleFit: 55,
        simplicity: 45,
        street: 75,
        volume: 70,
        comfort: 80,
        durability: 75,
        priceLevel: 55,
      },
      tags: ["trail", "outdoor", "chunky"],
      budgetFit: 80,
    },
  },
  caseC: {
    C1_comfort_runner: {
      sneakerId: "C1_comfort_runner",
      name: "Comfort Runner",
      vector: {
        culture: 55,
        styleFit: 70,
        simplicity: 65,
        street: 35,
        volume: 45,
        comfort: 92,
        durability: 88,
        priceLevel: 70,
      },
      tags: ["running", "comfortable", "durable"],
      budgetFit: 75,
    },
    C2_culture_low_comfort: {
      sneakerId: "C2_culture_low_comfort",
      name: "Culture High Low Comfort",
      vector: {
        culture: 95,
        styleFit: 55,
        simplicity: 45,
        street: 65,
        volume: 60,
        comfort: 35,
        durability: 45,
        priceLevel: 40,
      },
      tags: ["heritage", "retro", "basketball"],
      budgetFit: 75,
    },
    C3_premium_comfort: {
      sneakerId: "C3_premium_comfort",
      name: "Premium Comfort Model",
      vector: {
        culture: 60,
        styleFit: 75,
        simplicity: 60,
        street: 40,
        volume: 50,
        comfort: 90,
        durability: 85,
        priceLevel: 95,
      },
      tags: ["comfortable", "premium", "running"],
      budgetFit: 75,
    },
  },
  caseD: {
    D1_high_overlap_buy_to_wait: {
      sneakerId: "D1_high_overlap_buy_to_wait",
      name: "High Overlap Buy To Wait",
      vector: {
        culture: 70,
        styleFit: 82,
        simplicity: 82,
        street: 38,
        volume: 25,
        comfort: 80,
        durability: 78,
        priceLevel: 35,
      },
      tags: ["low_tech", "canvas", "classic", "minimal"],
      budgetFit: 90,
    },
  },
  caseE: {
    E1_low_price_fit_buy_to_wait: {
      sneakerId: "E1_low_price_fit_buy_to_wait",
      name: "Low Price Fit Buy To Wait",
      vector: {
        culture: 72,
        styleFit: 82,
        simplicity: 76,
        street: 52,
        volume: 42,
        comfort: 90,
        durability: 88,
        priceLevel: 100,
      },
      tags: ["premium", "comfortable", "classic"],
      budgetFit: 70,
    },
  },
  caseF: {
    F1_low_comfort_buy_to_wait: {
      sneakerId: "F1_low_comfort_buy_to_wait",
      name: "Low Comfort Buy To Wait",
      vector: {
        culture: 82,
        styleFit: 86,
        simplicity: 72,
        street: 62,
        volume: 52,
        comfort: 35,
        durability: 90,
        priceLevel: 30,
      },
      tags: ["heritage", "street", "classic"],
      budgetFit: 90,
    },
  },
  caseG: {
    G1_low_durability_buy_to_wait: {
      sneakerId: "G1_low_durability_buy_to_wait",
      name: "Low Durability Buy To Wait",
      vector: {
        culture: 82,
        styleFit: 86,
        simplicity: 72,
        street: 62,
        volume: 52,
        comfort: 90,
        durability: 40,
        priceLevel: 30,
      },
      tags: ["heritage", "street", "classic"],
      budgetFit: 90,
    },
  },
} as const;
