import { describe,expect,it } from "vitest";import { canonicalSneakerKey } from "../identity/canonicalSneaker";import type { ReleaseCandidate } from "../release/release";import { DAILY_PICK_ALGORITHM_VERSION,scoreDailyPick,selectDiverseDailyPicks,type DailyPickContext } from "./dailyPicks";
const context:DailyPickContext={favoriteBrands:["New Balance"],avoidedBrands:[],favoriteColors:["grey"],avoidedColors:["orange"],favoriteMaterials:["suede"],avoidedMaterials:["plastic"],budgetMaxJpy:30000,budgetIsHardLimit:false,owned:[],disliked:[],wishlist:[]};
function candidate(id:string,overrides:Partial<ReleaseCandidate>={}):ReleaseCandidate{const brand=overrides.brand??"New Balance",modelName=overrides.modelName??`Model ${id}`;return{id,key:canonicalSneakerKey({brand,modelName,modelFamily:overrides.key?.modelFamily??`family-${id}`,generation:"v1",audience:"unisex"}),brand,modelName,colorwayName:"Grey",informationState:"official_announced",releaseDate:"2099-01-01",verificationState:"verified",sourceConfidence:90,evidenceCount:2,priceJpy:20000,tags:[],colors:["grey"],materials:["suede"],...overrides}}
describe("daily pick scoring",()=>{
 it("uses the locked algorithm version",()=>expect(DAILY_PICK_ALGORITHM_VERSION).toBe("daily-picks-v1.0.0"));
 it.each(["official_announced","retailer_confirmed","editorial_reported","rumor","released","restocked","cancelled","date_changed","unknown","conflicting_evidence"] as const)("scores state %s deterministically",(informationState)=>{const a=scoreDailyPick(candidate(informationState,{informationState}),context);const b=scoreDailyPick(candidate(informationState,{informationState}),context);expect(a).toEqual(b);expect(a?.score.total).toBeGreaterThanOrEqual(0)});
 it("surfaces the required conflict caution without resolving a date",()=>{const result=scoreDailyPick(candidate("conflict",{informationState:"conflicting_evidence",releaseDate:null,hasConflict:true}),context);expect(result?.explanation.cautions).toContain("発売日は情報源によって異なります");expect(result?.candidate.releaseDate).toBeNull()});
 it.each(Array.from({length:20},(_,i)=>i))("keeps score components bounded case %i",(i)=>{const p=scoreDailyPick(candidate(`bound-${i}`,{sourceConfidence:i*7,colors:i%2?["grey"]:["orange"],materials:i%3?["suede"]:["plastic"]}),context)!;for(const [key,value] of Object.entries(p.score)){if(key!=="budgetFit"&&key!=="negativeFeedbackPenalty"&&key!=="duplicatePenalty")expect(value).toBeGreaterThanOrEqual(0)}});
 it.each(Array.from({length:10},(_,i)=>10000+i*10000))("hard budget rejects %i",(priceJpy)=>{const c={...context,budgetMaxJpy:5000,budgetIsHardLimit:true};expect(scoreDailyPick(candidate(`budget-${priceJpy}`,{priceJpy}),c)).toBeNull()});
 it.each(["grey","black","white","navy","green","brown","cream","red","blue","yellow"])("preferred color %s never lowers score",(color)=>{const c={...context,favoriteColors:[color]};const preferred=scoreDailyPick(candidate(`color-${color}`,{colors:[color]}),c)!;const neutral=scoreDailyPick(candidate(`neutral-${color}`,{colors:[]}),c)!;expect(preferred.score.total).toBeGreaterThanOrEqual(neutral.score.total)});
 it.each(["suede","canvas","leather","mesh","nubuck","wool","hemp","denim","rubber","synthetic"])("preferred material %s never lowers score",(material)=>{const c={...context,favoriteMaterials:[material]};expect(scoreDailyPick(candidate(`material-${material}`,{materials:[material]}),c)!.score.total).toBeGreaterThanOrEqual(scoreDailyPick(candidate(`neutral-material-${material}`,{materials:[]}),c)!.score.total)});
 it.each(["991","991v2","990v3","990v4","Samba OG","Samba ADV","Authentic","Authentic 44 DX","Air Jordan 1 Low","Air Jordan 1 Low Golf"])("exact owned duplicate %s is not selected",(modelName)=>{const item=candidate(`owned-${modelName}`,{modelName,key:canonicalSneakerKey({brand:"Test",modelName,audience:"unknown"})});const scored=scoreDailyPick(item,{...context,owned:[item.key]})!;expect(scored.score.duplicatePenalty).toBeGreaterThan(0);expect(selectDiverseDailyPicks([scored])).toEqual([])});
 it.each(Array.from({length:24},(_,i)=>i))("diversity matrix case %i",(i)=>{const list=Array.from({length:20},(_,j)=>{const brand=`Brand ${j%4}`,family=`family-${j%6}`;return scoreDailyPick(candidate(`${i}-${j}`,{brand,key:canonicalSneakerKey({brand,modelName:`Model ${j}`,modelFamily:family,audience:"unknown"}),informationState:j%5===0?"rumor":"official_announced"}),context)!});const selected=selectDiverseDailyPicks(list);expect(selected.length).toBeLessThanOrEqual(8);const brands=new Map<string,number>(),families=new Map<string,number>();for(const p of selected){brands.set(p.candidate.key.brandSlug,(brands.get(p.candidate.key.brandSlug)??0)+1);families.set(p.candidate.key.modelFamily,(families.get(p.candidate.key.modelFamily)??0)+1)}expect(Math.max(...brands.values())).toBeLessThanOrEqual(3);expect(Math.max(...families.values())).toBeLessThanOrEqual(2);expect(selected.filter(p=>p.candidate.informationState==="rumor").length).toBeLessThanOrEqual(2)});
 it.each(Array.from({length:10},(_,i)=>i))("does not invent candidates for short list %i",(size)=>{const list=Array.from({length:size},(_,j)=>scoreDailyPick(candidate(`short-${size}-${j}`),context)!);expect(selectDiverseDailyPicks(list).length).toBeLessThanOrEqual(size)});
});
