import { compareCanonicalSneakers,type CanonicalSneakerKey } from "../identity/canonicalSneaker";import type { ReleaseCandidate } from "../release/release";
export const DAILY_PICK_ALGORITHM_VERSION="daily-picks-v1.0.0";
export type DailyPickScore={tasteAffinity:number;explicitPreferenceFit:number;collectionNovelty:number;releaseUrgency:number;availabilityConfidence:number;evidenceConfidence:number;budgetFit:number|null;negativeFeedbackPenalty:number;duplicatePenalty:number;total:number};
export type DailyPickContext={favoriteBrands:string[];avoidedBrands:string[];favoriteColors:string[];avoidedColors:string[];favoriteMaterials:string[];avoidedMaterials:string[];budgetMaxJpy:number|null;budgetIsHardLimit:boolean;owned:CanonicalSneakerKey[];disliked:CanonicalSneakerKey[];wishlist:CanonicalSneakerKey[]};
export type ScoredDailyPick={candidate:ReleaseCandidate;score:DailyPickScore;explanation:{reasons:string[];cautions:string[]}};
export function scoreDailyPick(candidate:ReleaseCandidate,context:DailyPickContext):ScoredDailyPick|null{
 const disliked=context.disliked.some((key)=>["exact_style_code","exact_model"].includes(compareCanonicalSneakers(candidate.key,key)));if(disliked)return null;
 const ownedMatches=context.owned.map((key)=>compareCanonicalSneakers(candidate.key,key));const exactOwned=ownedMatches.some((m)=>m==="exact_style_code"||m==="exact_model");
 if(context.budgetIsHardLimit&&context.budgetMaxJpy!==null&&candidate.priceJpy!==null&&candidate.priceJpy>context.budgetMaxJpy)return null;
 const brandPreferred=context.favoriteBrands.some((v)=>norm(v)===norm(candidate.brand));const brandAvoided=context.avoidedBrands.some((v)=>norm(v)===norm(candidate.brand));
 const preferredColors=overlap(candidate.colors,context.favoriteColors),avoidedColors=overlap(candidate.colors,context.avoidedColors);const preferredMaterials=overlap(candidate.materials,context.favoriteMaterials),avoidedMaterials=overlap(candidate.materials,context.avoidedMaterials);
 const taste=clamp(55+preferredColors*12+preferredMaterials*12-avoidedColors*18-avoidedMaterials*18);
 const explicit=clamp(50+(brandPreferred?25:0)-(brandAvoided?40:0)+preferredColors*8+preferredMaterials*8-avoidedColors*20-avoidedMaterials*20);
 const collectionNovelty=exactOwned?0:ownedMatches.includes("family_related")?62:90;const urgency=releaseUrgency(candidate);const availability=availabilityConfidence(candidate);const evidence=evidenceConfidence(candidate);
 const budgetFit=candidate.priceJpy===null||context.budgetMaxJpy===null?null:clamp(100-(Math.max(0,candidate.priceJpy-context.budgetMaxJpy)/Math.max(1,context.budgetMaxJpy))*100);
 const negativeFeedbackPenalty=0,duplicatePenalty=exactOwned?75:0;const total=round(clamp(taste*.30+explicit*.20+collectionNovelty*.15+urgency*.10+availability*.10+evidence*.15-negativeFeedbackPenalty-duplicatePenalty));
 const reasons=[brandPreferred?"登録した好きなブランドです。":null,preferredColors?"登録した色の好みに近いです。":null,preferredMaterials?"登録した素材の好みに合います。":null,context.wishlist.some((k)=>compareCanonicalSneakers(candidate.key,k)!=="none")?"Wishlistに近い候補です。":null,!exactOwned?"所有済みの同一モデルではありません。":null].filter((v):v is string=>Boolean(v)).slice(0,3);
 const cautions=[candidate.informationState==="rumor"?"未確定情報で、公式発表ではありません。":null,candidate.verificationState!=="verified"?"配色は確認中です。":null,candidate.priceJpy===null?"予算との比較に必要な価格は未確認です。":null,exactOwned?"所有済みと同一のため優先度を下げました。":null].filter((v):v is string=>Boolean(v)).slice(0,3);
 return{candidate,score:{tasteAffinity:taste,explicitPreferenceFit:explicit,collectionNovelty,releaseUrgency:urgency,availabilityConfidence:availability,evidenceConfidence:evidence,budgetFit,negativeFeedbackPenalty,duplicatePenalty,total},explanation:{reasons,cautions}};
}
export function selectDiverseDailyPicks(candidates:ScoredDailyPick[],options={maxTotal:8,maxPerBrand:3,maxPerModelFamily:2,minimumOfficialCount:2,maximumRumorCount:2}){
 const sorted=[...candidates].sort((a,b)=>b.score.total-a.score.total||a.candidate.id.localeCompare(b.candidate.id));const chosen:ScoredDailyPick[]=[];const brand=new Map<string,number>(),family=new Map<string,number>();let rumors=0;
 const add=(item:ScoredDailyPick)=>{const b=item.candidate.key.brandSlug,f=item.candidate.key.modelFamily;if((brand.get(b)??0)>=options.maxPerBrand||(family.get(f)??0)>=options.maxPerModelFamily)return false;if(item.candidate.informationState==="rumor"&&rumors>=options.maximumRumorCount)return false;if(item.score.duplicatePenalty>0)return false;chosen.push(item);brand.set(b,(brand.get(b)??0)+1);family.set(f,(family.get(f)??0)+1);if(item.candidate.informationState==="rumor")rumors++;return true};
 const official=sorted.filter((i)=>["official_announced","retailer_confirmed","released","restocked","date_changed"].includes(i.candidate.informationState));for(const item of official){if(chosen.length>=Math.min(options.minimumOfficialCount,official.length))break;add(item)}for(const item of sorted){if(chosen.length>=options.maxTotal)break;if(!chosen.includes(item))add(item)}return chosen;
}
function releaseUrgency(c:ReleaseCandidate){if(c.informationState==="cancelled")return 0;if(["released","restocked"].includes(c.informationState))return 90;if(!c.releaseDate)return 35;const days=Math.ceil((Date.parse(c.releaseDate)-Date.now())/86400000);return days<0?40:days<=7?100:days<=30?80:55;}
function availabilityConfidence(c:ReleaseCandidate){return c.informationState==="official_announced"?90:c.informationState==="retailer_confirmed"?85:c.informationState==="released"||c.informationState==="restocked"?95:c.informationState==="rumor"?20:50;}
function evidenceConfidence(c:ReleaseCandidate){const capped=clamp(c.sourceConfidence);return c.informationState==="rumor"?Math.min(35,capped):c.verificationState==="verified"?capped:Math.min(65,capped);}
function overlap(a:string[],b:string[]){const s=new Set(b.map(norm));return a.filter((v)=>s.has(norm(v))).length}function norm(v:string){return v.normalize("NFKC").toLowerCase().trim()}function clamp(v:number){return Math.max(0,Math.min(100,v))}function round(v:number){return Math.round(v*10)/10}
